import './globals.css'
import type { Metadata } from 'next'
import { Aldrich, Montserrat } from 'next/font/google'
//comoponents
import Navbar from './components/Navbar'
const aldrich = Aldrich({ subsets: ['latin'] ,weight:['400']})
const montserrat=Montserrat({subsets:['latin'],weight:['400']})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={aldrich.className}>
        <Navbar  />
        {children}
        </body>
    </html>
  )
}
